### ISSUE TITLE
Statfs system call  not support

### ISSUE THREAD

**Issue by ParkerXie** [edgelesssys/ego#146] opened 2022-06-27 10:35 UTC
When build and run  program with ego ,we can't get disk info with 'Statfs'  system call,it will return the error:function not implemented.
sample code:
```golang
import (
        "fmt"
        "golang.org/x/sys/unix"
)
func main() {
        status :=DiskUsage("/")
        fmt.Println(status)
}


// disk usage of path/disk
func DiskUsage(path string) (disk DiskStatus) {
	fs := unix.Statfs_t{}
	err := unix.Statfs(path, &fs)
	if err != nil {
           fmt.Println(err)
		return
	}
	disk.All = fs.Blocks * uint64(fs.Bsize)
	disk.Free = fs.Bfree * uint64(fs.Bsize)
	disk.Used = disk.All - disk.Free
	return
}

**Comment by thomasten** [comment] 2022-06-27 12:35
I can confirm that statfs isn't supported yet. I'm not sure how statfs should behave inside an enclave, given that you have hostfs (which you can't trust) and memfs (for which you can't get precise stat values). I'd probably prefer an implementation that returns reasonable dummy values. This should be sufficient to satisfy existing code to not fail because of a statfs call.
What are your requirements? Would such an implementation work for you?

**Comment by ParkerXie** [comment] 2022-06-28 02:37
Thank you for your reply. We use statfs  to obtain the remaining disk space, and then determine whether disk GC needs to be enabled. If statfs can't be supported with ego,we will try to modify the disk GC policy.

**Comment by thomasten** [comment] 2022-06-28 07:31
How about this: You can call statfs with a prefix, e.g.,  `/edg/hostfs/foo/bar`. The syscall will be forwarded to the host on `/foo/bar`, ignoring configured mounts in enclave.json. Without the prefix, you'll get dummy values.

Existing enclave-unaware code would get dummy values that don't need to be checked and are enough to prevent the code failing. But you are also able to get the actual values from the host. As with all data coming from the host, you should carefully check it before taking actions on it.

Would this work for you?

**Comment by ParkerXie** [comment] 2022-06-28 11:23
@thomasten Yes,it will work for me.

**Comment by thomasten** [comment] 2022-07-06 14:54
This is implemented in master and will be part of the next release.

**Comment by ParkerXie** [comment] 2022-07-07 09:19
@thomasten thank you very much

**Comment by thomasten** [comment] 2022-07-19 08:21
Added in v1.0.0. See behavior: https://docs.edgeless.systems/ego/#/knowledge/limitations?id=statfs

**Closed** 2022-07-21 08:11 UTC
