### ISSUE TITLE
openenclave/attestation/verifier.h: No such file or directory

### ISSUE THREAD

**Issue by hello2mao** [edgelesssys/ego#107] opened 2022-01-07 07:44 UTC
### Issue description

```
/usr/local/go/pkg/mod/github.com/edgelesssys/ego@v0.4.0/eclient/ert.go:10:11: fatal error: openenclave/attestation/verifier.h: No such file or directory
 // #include <openenclave/attestation/verifier.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
But:
```
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation# pwd
/opt/openenclave/include/openenclave/attestation
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation# ls
attester.h  custom_claims.h  sgx  verifier.h
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation#
```

**Comment by thomasten** [comment] 2022-01-07 16:33
Hi @hello2mao,
When using the eclient package, you must set CGO_CFLAGS and CGO_LDFLAGS like in the [remote attestation sample](https://github.com/edgelesssys/ego/tree/master/samples/remote_attestation). I just realized that this is missing in the package doc; will add this.

**Comment by hello2mao** [comment] 2022-01-09 07:34
> Hi @hello2mao, When using the eclient package, you must set CGO_CFLAGS and CGO_LDFLAGS like in the [remote attestation sample](https://github.com/edgelesssys/ego/tree/master/samples/remote_attestation). I just realized that this is missing in the package doc; will add this.

```
CGO_CFLAGS=-I/opt/ego/include CGO_LDFLAGS=-L/opt/ego/lib go build main.go
```
Works for `github.com/edgelesssys/ego v0.2.2`
But failed for `github.com/edgelesssys/ego v0.4.0`

Errors:
```
# github.com/edgelesssys/ego/eclient
/usr/local/go/pkg/mod/github.com/edgelesssys/ego@v0.4.0/eclient/ert.go:10:11: fatal error: openenclave/attestation/verifier.h: No such file or directory
 // #include <openenclave/attestation/verifier.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by thomasten** [comment] 2022-01-09 15:05
Thanks, I can now reproduce the error. This will be fixed with the next release. Until then, you can use v0.3.4 of the module.

**Comment by thomasten** [comment] 2022-02-07 09:18
fixed in v0.4.1

**Closed** 2022-02-24 09:12 UTC

**Comment by tabz11** [comment] 2024-03-06 14:06
I am getting the same error in v1.4.4

**Comment by thomasten** [comment] 2024-03-10 16:30
@tabz11 It works for me with v1.4.4. Is it one of the samples you're trying to build?
Does building the remote_attestation sample with
```
CGO_CFLAGS=-I/opt/ego/include CGO_LDFLAGS=-L/opt/ego/lib go build ra_client/client.go
```
work for you?
